## Loading Data from local file

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./XYmat.csv')

In [21]:
df.head(5)

name  reviews  Dungeons & Dragons  \
0               PLAYERUNKNOWN'S BATTLEGROUNDS       92                   0   
1                                  BATTLETECH       49                   0   
2                                        DayZ       71                   0   
3                                  EVE Online       61                   0   
4  Grand Theft Auto V: Premium Online Edition       74                   0   

   Dynamic Narration  Hacking  Otome  Benchmark  Western  Lemmings  Mystery  \
0                  0        0      0          0        0         0        0   
1                  0        0      0          0        0         0        0   
2                  0        0      0          0        0         0        0   
3                  0        0      0          0        0         0        0   
4                  0        0      0          0        0         0        0   

   ...  Futuristic  World War II  Match 3  Illuminati  Modern  Competitive  \
0  ...           0             0        0           0       0            1   
1  ...           1             0        0           0       0            0   
2  ...           0             0        0           0       0            0   
3  ...           0             0        0           0       0            0   
4  ...           0             0        0           0       0            0   

   Hardware  Choices Matter  Violent  Artificial Intelligence  
0         0               0        0                        0  
1         0               0        0                        0  
2         0               0        0                        0  
3         0               0        0                        0  
4         0               0        0                        0  

[5 rows x 383 columns]

In [ ]:
df.columns

In [8]:
df.index

RangeIndex(start=0, stop=17371, step=1)

In [9]:
df.values

array([["PLAYERUNKNOWN'S BATTLEGROUNDS", 92, 0, ..., 0, 0, 0],
       ['BATTLETECH', 49, 0, ..., 0, 0, 0],
       ['DayZ', 71, 0, ..., 0, 0, 0],
       ...,
       ['Rivals of Aether: Summit Orcane', 90, 0, ..., 0, 0, 0],
       ['Space Cat', 70, 0, ..., 0, 0, 0],
       ['White Day - Horror Costume - Ji-Min Yoo', 28, 0, ..., 0, 0, 0]],
      dtype=object)

In [62]:
y = df['reviews'].values
array = df.to_numpy()
X = array[:, 2:]
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Split train test data

In [63]:
Xtrain = X[:12160]
Xtest = X[12160:]
ytrain = y[:12160]
ytest = y[12160:]
print(Xtrain.shape, Xtest.shape, ytrain.shape, ytest.shape)

(12160, 381) (5211, 381) (12160,) (5211,)


## Test data with multiple linear regression

In [71]:
import scipy as sp
import scipy.sparse.linalg
import math

In [72]:
out = sp.sparse.linalg.lsqr(Xtrain,ytrain)
beta = out[0]
print(beta.shape)

(381,)


## Compute Baseline

In [85]:
yBaseline = np.ones(len(ytest)) * np.mean(ytrain)
errs = np.array(abs(ytest - yBaseline))
loss = np.sum(errs)
avgL = loss/len(ytest)
print("multiple variable loss="+"{:.2e}".format(avgL))

multiple variable loss=2.85e+01


In [ ]:
## 

In [79]:
yp = np.dot(Xtest,beta)
errs = np.array(abs(ytest - yp))
loss = np.sum(errs)
avgL = loss/len(ytest)

print("multiple variable loss="+"{:.2e}".format(avgL))
for i in range(50):
    print(ytest[i], yp[i], abs(yp[i]-ytest[i]))

multiple variable loss=2.65e+01
75 66.88346038409163 8.116539615908366
70 67.56845067598267 2.4315493240173254
79 94.29443959262494 15.29443959262494
77 27.327110195429903 49.6728898045701
71 70.53734822416538 0.46265177583461536
78 45.54536602941934 32.45463397058066
71 103.13783266619402 32.137832666194015
79 48.738699188088 30.261300811912
77 66.00062352451604 10.999376475483956
75 72.57730156806224 2.4226984319377607
79 11.857866846952115 67.14213315304788
77 40.03540058331781 36.96459941668219
76 39.5013891264449 36.4986108735551
75 18.94017999438423 56.05982000561577
78 17.854063981236052 60.14593601876395
77 11.857866846952115 65.14213315304788
77 11.857866846952115 65.14213315304788
78 47.58284023987652 30.417159760123482
77 45.56259280271968 31.437407197280322
75 21.19885550013045 53.80114449986955
76 23.054814262200296 52.945185737799704
75 48.56139779972086 26.438602200279142
73 60.91239516096326 12.087604839036743
78 76.85999309950097 1.1400069004990314
76 111.5749830074450