## Loading Data from local file

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./XYmat.csv')

In [21]:
df.head(5)

name  reviews  Dungeons & Dragons  \
0               PLAYERUNKNOWN'S BATTLEGROUNDS       92                   0   
1                                  BATTLETECH       49                   0   
2                                        DayZ       71                   0   
3                                  EVE Online       61                   0   
4  Grand Theft Auto V: Premium Online Edition       74                   0   

   Dynamic Narration  Hacking  Otome  Benchmark  Western  Lemmings  Mystery  \
0                  0        0      0          0        0         0        0   
1                  0        0      0          0        0         0        0   
2                  0        0      0          0        0         0        0   
3                  0        0      0          0        0         0        0   
4                  0        0      0          0        0         0        0   

   ...  Futuristic  World War II  Match 3  Illuminati  Modern  Competitive  \
0  ...           0             0        0           0       0            1   
1  ...           1             0        0           0       0            0   
2  ...           0             0        0           0       0            0   
3  ...           0             0        0           0       0            0   
4  ...           0             0        0           0       0            0   

   Hardware  Choices Matter  Violent  Artificial Intelligence  
0         0               0        0                        0  
1         0               0        0                        0  
2         0               0        0                        0  
3         0               0        0                        0  
4         0               0        0                        0  

[5 rows x 383 columns]

In [ ]:
df.columns

In [8]:
df.index

RangeIndex(start=0, stop=17371, step=1)

In [9]:
df.values

array([["PLAYERUNKNOWN'S BATTLEGROUNDS", 92, 0, ..., 0, 0, 0],
       ['BATTLETECH', 49, 0, ..., 0, 0, 0],
       ['DayZ', 71, 0, ..., 0, 0, 0],
       ...,
       ['Rivals of Aether: Summit Orcane', 90, 0, ..., 0, 0, 0],
       ['Space Cat', 70, 0, ..., 0, 0, 0],
       ['White Day - Horror Costume - Ji-Min Yoo', 28, 0, ..., 0, 0, 0]],
      dtype=object)

In [62]:
y = df['reviews'].values
array = df.to_numpy()
X = array[:, 2:]
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Split train test data

In [63]:
Xtrain = X[:12160]
Xtest = X[12160:]
ytrain = y[:12160]
ytest = y[12160:]
print(Xtrain.shape, Xtest.shape, ytrain.shape, ytest.shape)

(12160, 381) (5211, 381) (12160,) (5211,)


## Test data with multiple linear regression

In [71]:
import scipy as sp
import scipy.sparse.linalg
import math

In [72]:
out = sp.sparse.linalg.lsqr(Xtrain,ytrain)
beta = out[0]
print(beta.shape)

(381,)


## Compute Baseline

In [85]:
yBaseline = np.ones(len(ytest)) * np.mean(ytrain)
errs = np.array(abs(ytest - yBaseline))
loss = np.sum(errs)
avgL = loss/len(ytest)
print("multiple variable loss="+"{:.2e}".format(avgL))

multiple variable loss=2.85e+01


In [86]:
## Compute loss with linear regression

In [87]:
yp = np.dot(Xtest,beta)
errs = np.array(abs(ytest - yp))
loss = np.sum(errs)
avgL = loss/len(ytest)

print("multiple variable loss="+"{:.2e}".format(avgL))
#for i in range(50):
    #print(ytest[i], yp[i], abs(yp[i]-ytest[i]))

multiple variable loss=2.65e+01
